{application,test,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{test_app,[]}},
              {applications,[kernel,stdlib,cowboy]},
              {env,[]},
              {modules,[publiser,rabbitmq_factory,test,test_app,test_handler,
                        test_sup]},
              {maintainers,[]},
              {licenses,[]},
              {links,[]}]}.
